name: NodeJS CI

on:
  push:
    branches:
     - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install code dependencies
      run: npm install

    - name: Run code tests
      run: npm test